site:
  name: MobileHeads Austria
  site: "https://mobileheads.at"
  base: "/"
  trailingSlash: false
  contactEmail: "ask@mobileheads.at"

  googleSiteVerificationId: null #aaa-bbb-ccc

analytics:
  vendors:
    googleAnalytics:
      id: "G-SQMQNLHRPT"

ui:
  theme: "light:only" # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
