metadata:
  title:
    default: Mobileheads Austria
    template: "%s — Mobileheads Austria"
  description: "Mobileheads Austria is Austria’s leading mobile development community. We celebrate all aspects of mobile technology, from native app development to hybrid solutions and beyond!\nOur community thrives on collaboration and inclusivity. Whether you’re using Swift, Kotlin, Flutter, React Native, or experimenting with your own innovative tools—Mobileheads is the perfect platform to share, learn, and grow"
  robots:
    index: true
    follow: true
  openGraph:
    site_name: MobileHeads Austria
    images:
      - url: "~/assets/images/hero.png"
        width: 1200
        height: 628
    type: website
  twitter:
    handle: "@onwidget"
    site: "@onwidget"
    cardType: summary_large_image
